export { LoginPage } from './auth/LoginPage';
export { RegisterPage } from './auth/RegisterPage';
export { ForgotPasswordPage } from './auth/ForgotPasswordPage';
export { ResetPasswordPage } from './auth/ResetPasswordPage';
export { VerifyEmailPage } from './auth/VerifyEmailPage';
export { DashboardPage } from './dashboard/DashboardPage';
export { ProfilePage } from './profile/ProfilePage';
export { NotFoundPage } from './NotFoundPage';
export { CoursesPage } from './courses/CoursesPage';
export { CourseDetailPage } from './courses/CourseDetailPage';
export { MyCoursesPage } from './courses/MyCoursesPage';
export { MySectionsPage } from './courses/MySectionsPage';
export { CompletedCoursesPage } from './courses/CompletedCoursesPage';
export { GradesPage } from './grades/GradesPage';
export { GradebookPage } from './grades/GradebookPage';
export { StartAttendancePage } from './attendance/StartAttendancePage';
export { GiveAttendancePage } from './attendance/GiveAttendancePage';
export { MyAttendancePage } from './attendance/MyAttendancePage';
export { AttendanceReportPage } from './attendance/AttendanceReportPage';
export { ExcuseRequestsPage } from './attendance/ExcuseRequestsPage';
export { ActiveSessionsPage } from './attendance/ActiveSessionsPage';
export { ScanQRCodePage } from './attendance/ScanQRCodePage';
export { CourseManagementPage } from './admin/CourseManagementPage';
export { SectionManagementPage } from './admin/SectionManagementPage';
export { DepartmentManagementPage } from './admin/DepartmentManagementPage';
export { StudentManagementPage } from './admin/StudentManagementPage';
export { default as MealManagementPage } from './admin/MealManagement';
export { default as MealReservationPage } from './MealReservation';
export { default as MealScannerPage } from './admin/MealScanner';
export { default as WalletPage } from './WalletPage';
export { default as PaymentMockPage } from './PaymentMockPage';
export { EventListPage } from './events/EventListPage';
export { EventDetailPage } from './events/EventDetailPage';
export { MyTicketsPage } from './events/MyTicketsPage';
export { EventCheckInPage } from './events/EventCheckInPage';
export { EventManagementPage } from './admin/EventManagementPage';
export { ClassroomReservationPage } from './reservations/ClassroomReservationPage';
export { MySchedulePage } from './schedule/MySchedulePage';
export { GenerateSchedulePage } from './schedule/GenerateSchedulePage';
export { ClassroomManagementPage } from './admin/ClassroomManagementPage';
export { ReservationApprovalPage } from './admin/ReservationApprovalPage';
export { AdminDashboardPage, AcademicPerformancePage, AttendanceAnalyticsPage, MealAnalyticsPage, EventAnalyticsPage } from './admin/analytics';

